### ISSUE TITLE
Vanilla worlds don't load properly

### ISSUE THREAD

**Issue by PlPiP** [Bro748/World-Editor-Github#1]
Only showing few rooms
![image](https://user-images.githubusercontent.com/82168615/227722962-19ee08cc-2c22-41a9-9db6-f30c30a45b0b.png)
Everything is fine in the MSC expansion worlds
The Rooms folder shows only rooms that were loaded
I tried deleting these files, didn't work 
I don't have any world changing mods installed

**Comment by PlPiP** [comment]
Hello?
Loading worlds in the mergedmods folder only shows changes that downpour added
![image](https://user-images.githubusercontent.com/82168615/228237553-e40a9d95-991b-40ec-b404-74d249abbf56.png)

**Comment by Bro748** [comment]
This bug should be resolved in the latest version 1.01
